import type { Metadata } from "next";
import "../style/globals.css";
import { CssBaseline } from "@mui/material";
import StyledComponentsRegistry from "./registry";
import Theme from "@/Theme/themeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Theme>
        <CssBaseline />
        <body>
          <StyledComponentsRegistry>
     
            {children}
          </StyledComponentsRegistry>
        </body>
      </Theme>
    </html>
  );
}
